version: '2'

services:
  samba:
    image: joebiellik/samba-server

    volumes:
      # You must provide a Samba config file
      - ./smb.conf:/etc/samba/smb.conf

     # Shares
      - ~/smbcshare:/mnt/smbcshare


    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"

    environment:
      - USERNAME=joe
      - PASSWORD=samba

     # Uncomment to override defaults
     # - UID=1000
     # - GID=1000
